### ISSUE TITLE
Gallery review feedback

### ISSUE THREAD

**Issue by delsonting** [getelevar/gtm-monitoring-core#3]
We received your submissions for the multiple Elevar tag templates for the Tag Manager Template Gallery. Can you help me understand how these templates work together and how many tags you plan on supporting? You can contact me at delson@google.com if email would be a better forum for discussion. Thanks.

**Comment by Aaronkala** [comment]
Hey @delsonting!

Over the next 6 months we will likely be supporting ~30-40 individual marketing channel tags. We use the validation on the individual tags to help populate the monitoring dashboard for our customers. Here's a quick snapshot - https://share.getcloudapp.com/d5uvWgZj

The idea behind the templates is to catch incorrect variable output and report them as errors to our monitoring solution.

We have three different types of templates:
**Variable Validation Template ([repo](https://github.com/getelevar/gtm-monitoring-variables))**
Add’s errors to the window if variable output doesn’t match the conditions set for them, for example product price should be a number or cart quantity is always required.

**The Additional Information Tags**
These tags (Facebook, Snapchat, Klaviyo...) implement the channel specific pixel functionality and in addition add extra information about the tags associated to the variable errors. For example the error with product price being undefined had an impact on the “Facebook - Purchase” tag.

**The Core Tag (this repo)**
Get’s all errors and the tag information associated with them and sends the data to our monitoring backend

---

Let me know if you want more info or have other questions :)

**Comment by delsonting** [comment]
Ah, thanks for the background here and good to understand the overall plan. My concern is the potential proliferation of templates for each tag provided in the Gallery making it difficult for users to find the right template for their needs. 

Can these tag specific templates can be combined into fewer templates or a single generic template that can be configured by your customers for the tags they have in their container? I'm sure you've thought about this much more than me, on the surface this would potentially make it easier for your customers to add monitoring to multiple tags without adding separate templates for each tag.

**Comment by Aaronkala** [comment]
@delsonting Yeah I understand the concern with having a new template in the gallery for each channel.

  We initially went through a few alternative methods on how we could get the tag information attached to the errors but ended up with this as the best alternative.  

1. We didn’t want to add extra bloat to their containers by using tag sequencing or separate the logic outside the tags.
 2. We didn’t want to combine all the channels into one tag due to privacy issues with permissions to inject any script from any channel.

  However, I took some time today to think if there still were some unexplored routes to this and ended up creating a new template that is powered by the “Additional Tag Metadata” field. With this template, we could possibly reduce our templates to only 3 different ones (core, tag data, and variable errors). We still, however, need to verify that it works like expected and catch potential issues.  

With that said, the [core tag template](https://github.com/getelevar/gtm-monitoring-core) and the [variable error template](https://github.com/getelevar/gtm-monitoring-variables) are still unaffected by this change and they function even without the tag data template(s) so the review process can continue for them if that is possible. The tag data template only provides additional information to the pixel.

—

Also, on a side note, do you have a forum or something for the GTM templates where I could submit suggestions or issues? I ran into a couple of issues that I think are bugs, that I could report. :)

**Comment by delsonting** [comment]
The core tag and variable error templates have been approved and should be live in the Template Gallery within 24 hours. I'll look out for a tag data template from you soon :)

For issues/suggestions you can file feedback in the Tag Manager Application, it's the overflow menu on the top right (3 vertical dots) -> Send Feedback. We do look at these and get them to the right place. We are actively adding more Template APIs so any input you have would be much appreciated. Also, there is an active slack channel (https://www.measure.chat/) that includes some of the more technical Tag Manager developers.
